version: '3.9'

services:
  rstudio: 
    image: n8layman/rstudio-server:latest
    container_name: rstudio_server
    ports:
      - "8787:8787"
    environment:
      - USERNAME=${USERNAME:-rstudio}
      - PASSWORD=${RSTUDIO_PASSWORD}
    volumes:
      - ${PERSISTENT_VOLUME:-~/Documents/projects}:/home/${USERNAME}/projects
    restart: unless-stopped