name: Build and Push RStudio Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'docker/rstudio/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build \
          --build-arg USER=${{ secrets.RSTUDIO_USER }} \
          --build-arg PASSWORD=${{ secrets.RSTUDIO_PASSWORD }} \
          -t ${{ secrets.DOCKER_USERNAME }}/rstudio-server:latest \
          ./docker/rstudio

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/rstudio-server:latest
