name: Process New Papers

on:
  push:
    paths:
      - 'resources/papers/**'
  workflow_dispatch:

jobs:
  process-papers:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.3.1  # Use a specific Rocker R version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required R packages
        run: |
          install.packages(c("pdftools", "httr", "stringr", "bibtex"), dependencies=TRUE, repos='http://cran.rstudio.com/')
        shell: Rscript {0}

      - name: Run R script
        run: Rscript scripts/process_papers.R
        shell: Rscript {0}